[2024-10-09 10:35:33,101] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_crypto_dag.DOGE scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-09 10:35:33,111] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_crypto_dag.DOGE scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-09 10:35:33,112] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 10:35:33,112] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-09 10:35:33,112] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 10:35:33,481] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): DOGE> on 2024-09-23 00:00:00+00:00
[2024-10-09 10:35:33,497] {standard_task_runner.py:52} INFO - Started process 60540 to run task
[2024-10-09 10:35:33,506] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_crypto_dag', 'DOGE', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/get_crypto.py', '--cfg-path', '/tmp/tmp5sjxgyhz', '--error-file', '/tmp/tmpxkuykbef']
[2024-10-09 10:35:33,508] {standard_task_runner.py:80} INFO - Job 400: Subtask DOGE
[2024-10-09 10:35:33,985] {task_command.py:370} INFO - Running <TaskInstance: get_crypto_dag.DOGE scheduled__2024-09-23T00:00:00+00:00 [running]> on host ken
[2024-10-09 10:35:34,479] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_crypto_dag
AIRFLOW_CTX_TASK_ID=DOGE
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-23T00:00:00+00:00
[2024-10-09 10:35:38,609] {history.py:122} ERROR - $DOGE: possibly delisted; no timezone found
[2024-10-09 10:35:48,622] {python.py:173} INFO - Done. Returned value was: None
[2024-10-09 10:35:49,098] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_crypto_dag, task_id=DOGE, execution_date=20240923T000000, start_date=20241009T133533, end_date=20241009T133549
[2024-10-09 10:35:49,135] {local_task_job.py:220} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-10-09 10:35:49,148] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 60540. PIDs of all processes in the group: [60540]
[2024-10-09 10:35:49,149] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 60540
[2024-10-09 10:35:49,149] {process_utils.py:75} INFO - Process psutil.Process(pid=60540, status='terminated', exitcode=0, started='10:35:33') (60540) terminated with exit code 0
