[2024-10-09 10:28:45,942] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: get_crypto_dag.BTC scheduled__2024-09-16T00:00:00+00:00 [scheduled]>, dependency 'Task Instance State' FAILED: Task is in the 'scheduled' state.
[2024-10-09 10:28:46,282] {local_task_job.py:101} INFO - Task is not able to be run
[2024-10-09 10:29:21,033] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_crypto_dag.BTC scheduled__2024-09-16T00:00:00+00:00 [queued]>
[2024-10-09 10:29:21,070] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_crypto_dag.BTC scheduled__2024-09-16T00:00:00+00:00 [queued]>
[2024-10-09 10:29:21,070] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 10:29:21,072] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-09 10:29:21,072] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 10:29:21,125] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BTC> on 2024-09-16 00:00:00+00:00
[2024-10-09 10:29:21,145] {standard_task_runner.py:52} INFO - Started process 51747 to run task
[2024-10-09 10:29:21,153] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_crypto_dag', 'BTC', 'scheduled__2024-09-16T00:00:00+00:00', '--job-id', '351', '--raw', '--subdir', 'DAGS_FOLDER/get_crypto.py', '--cfg-path', '/tmp/tmp1oa35la3', '--error-file', '/tmp/tmpbfcfsxd1']
[2024-10-09 10:29:21,156] {standard_task_runner.py:80} INFO - Job 351: Subtask BTC
[2024-10-09 10:29:21,648] {task_command.py:370} INFO - Running <TaskInstance: get_crypto_dag.BTC scheduled__2024-09-16T00:00:00+00:00 [running]> on host ken
[2024-10-09 10:29:21,944] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_crypto_dag
AIRFLOW_CTX_TASK_ID=BTC
AIRFLOW_CTX_EXECUTION_DATE=2024-09-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-16T00:00:00+00:00
[2024-10-09 10:29:22,699] {history.py:244} ERROR - $BTC: possibly delisted; no price data found  (1h 2024-09-15 -> 2024-09-16)
[2024-10-09 10:29:32,715] {python.py:173} INFO - Done. Returned value was: None
[2024-10-09 10:29:32,792] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_crypto_dag, task_id=BTC, execution_date=20240916T000000, start_date=20241009T132921, end_date=20241009T132932
[2024-10-09 10:29:32,890] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-09 10:29:33,855] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
